# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/cosma',
                'doc_host': 'https://la3d.github.io/',
                'git_url': 'https://github.com/la3d/cosma',
                'lib_path': 'cosma'},
  'syms': { 'cosma.core': { 'cosma.core.agent': ('agents.html#agent', 'cosma/core.py'),
                            'cosma.core.tool': ('agents.html#tool', 'cosma/core.py')}}}
